package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
)

func main() {
	flag.Parse()
	if flag.NArg() != 1 {
		usage()
	}

	// open files to read and write
	openup()
	fmt.Fprintf(ftable, "// Code generated by myacc %s. DO NOT EDIT.\n", strings.Join(os.Args[1:], " "))

	// define initial symbols
	defineInitialSymbols()

	// parse input file
	parseInput()

	// fix lookahead set size
	lksize = (termN + 32) / 32

	// process the productions
	procProds()

	// generate states
	stategen()

	// compute shifts, reductions, gotos and exception action table
	procStates()

	// compress goto table
	packGotosByCol()

	// store shifts and gotos in actionStore
	storeShiftsAndGotos()

	// write summary
	summary()

	// write the generated code for parser
	writeParser()

	// done 👏
	exit(0)
}
